services:
  - type: web
    name: bo-luang-municipal-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_DEMO_MODE
        value: "false"
      - key: VITE_SUPABASE_URL
        value: "https://emfjpppexfiiwrrgmnvo.supabase.co"
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: "sb_publishable_bYJBdPpmn6184y9fvrLMXg_aBwrNPpI"
